apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps1
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Argocd-multi-apps/kube-manifest/apps1
    repoURL: https://gitlab.com/ayush-sharma/example-assets.git
    targetRevision: HEAD
