apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps2
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Argocd-multi-apps/apps/apps2
    repoURL: https://github.com/ekh87/Argocd-multi-apps.git
    targetRevision: HEAD
