apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-02
  labels:
    app: apps2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apps2
  template:
    metadata:
      labels:
        app: apps2
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
